import './globals.css'
import { Inter } from 'next/font/google'
import { TaskProvider } from '@/context/TaskContext'
import { Navbar } from '@/components/Navbar'
import { Toaster } from './Toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Task App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} max-w-4xl mx-auto px-4`}>
        <TaskProvider>
          <Navbar />
          {children}
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  )
}
